### PR TITLE
🚀v1.0.0: Official launch of Livl Madness

### PR DESCRIPTION
**Pull request by jvondermarck**

### CODE REVIEW

**Review by Kayn017 — APPROVED** [review]
nul

**Review by Augustin68 — APPROVED** [review]
Such an amazing work, I have read every line of it it is so amazing love coeur miam jadore livl

**Review by jvondermarck — COMMENTED** [review]
Insane

**Review by FranckG28 — APPROVED** [review]
I'm so emoustillé 🔥

**Review by FranckG28 — APPROVED** [review]
I'm so emoustillé 🔥

**Pull request merged**
